### PR TITLE
Add snap packaging

### PR DESCRIPTION
**Pull request by artivis**
Add snap packaging together with the associated workflow.

The snap may be still a little rough but loading/saving mcap file works.
Let me know if you test it and find any issue.

The workflow will automatically publish the snap to the store if/once:
- you register the snap name `mcap-editor`
- create a store token as explained [here](https://github.com/snapcore/action-publish?tab=readme-ov-file#store-login)

### CODE REVIEW

**Comment by facontidavide** [comment]
Awesome

**Comment by facontidavide** [comment]
Seems to have an issue: https://github.com/facontidavide/mcap_editor/actions/runs/8003424007/job/21859531118#step:2:8

**Comment by artivis** [comment]
> Seems to have an issue: https://github.com/facontidavide/mcap_editor/actions/runs/8003424007/job/21859531118#step:2:8

I will look into it asap. At least it is only the very final cleanup step that failed. As a result, the artifact if available [here](https://github.com/facontidavide/mcap_editor/actions/runs/8003424007/artifacts/1266079731).

**Comment by szepilot** [comment]
If I'm not mistaken now I should be able to install it with `snap`. However, I am getting the following error: 
``` r
$ sudo snap install mcap-editor

error: snap "mcap-editor" not found
```

**Pull request merged**
